version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: "Set Python 3"
          command: pyenv global 3.7.0
      - run:
          name: Install docker-compose
          command: |
            set -x
            sudo apt-get install curl bash
            pip install docker-compose
      - run:
          name: Backend tests
          command: |
            set -x
            mv api/config/auth.yml.sample api/config/auth.yml
            chmod +x tools/backend_tests
            tools/backend_tests
      - run:
          name: Frontend tests
          command: |
            set -x
            chmod +x tools/frontend_tests
            tools/frontend_tests
